ATM.class: ATM.java
	javac ATM.java
Checking_Account.class: Checking_Account.java
	javac Checking_Account.java
Saving_Account.class: Savings_Account.java
	javac Savings_Account.java
User.class: User.java
	javac User.java

make run: ATM.class
	java ATM

make clean:
	rm *.class

